# -*- coding: utf-8 -*-
"""AncientWisdomBot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fe05y4Im7MPwxpUWdvk9ZZWbKeoUuM03
"""

# installing openai
!pip install "openai>=1.50.0" PyMuPDF requests matplotlib numpy pandas seaborn -q
print('Dependencies installed.')

from google.colab import userdata
Openai_API_KEY = userdata.get('Openai_API_KEY')
newsData_API_KEY = userdata.get('newsData_API_KEY')
Semantic_API_KEY = userdata.get('Semantic_API_KEY')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import os, json, time, re, requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from pathlib import Path
from openai import OpenAI

client = OpenAI(api_key=Openai_API_KEY)
print(f'   OpenAI version: {__import__("openai").__version__}')

from google.colab import drive

drive.mount('/content/drive')

DRIVE_FOLDER = ["/content/drive/MyDrive/Colab Notebooks/Ancient Wisdom Corpus",
"/content/drive/MyDrive/Colab Notebooks/Bridging corpus"]

# I create nicknames for the path to each folder
ANCIENT_PATH = DRIVE_FOLDER[0]
BRIDGE_PATH = DRIVE_FOLDER[1]

vector_store = client.vector_stores.create(name="Ancient Wisdom Full Corpus")

# 1. I first divide the files from each path so that Python can find its way to each folder.
ancient_files = [
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book I_Defining eudaimonia and the aim of Ethics.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book II-III_Excellence of character or moral virtue -voluntary and involuntary actions.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book IV_second set of examples of moral virtues.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book V_Justice and Fairness.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book VI_Intellectual Virtues.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book VII_Impediments to virtue.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Books VIII and IX_Friendship.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_NichomacheanEthics-Book X_Pleasure, happiness, and upbringing.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric_1.Foundations and History.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric_2.Mutual Relations and Core Concepts.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric_3.Analysis of Rhetoric Book I & Appendices.pdf"),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric_4.Analysis of Rhetoric Book II.pdf" ),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric_5.Analysis of Rhetoric Book III.pdf" ),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric_6.Appendices to Book III.pdf" ),
    os.path.join(ANCIENT_PATH, "Aristotle_Rhetoric.7_Rhetorica ad Alexandrum.pdf" ),
    os.path.join(ANCIENT_PATH, "Buddharakkhita_Dhammapada-1.Introduction and Basics.pdf" ),
    os.path.join(ANCIENT_PATH, "Buddharakkhita_Dhammapada-2.The Path of the Individual.pdf" ),
    os.path.join(ANCIENT_PATH, "Buddharakkhita_Dhammapada-3.Higher Teachings and Virtues.pdf" ),
    os.path.join(ANCIENT_PATH, "Buddharakkhita_Dhammapada-4.Final considerations.pdf" ),
    os.path.join(ANCIENT_PATH, "Epitectus_TheEnchiridion.pdf" ),
    os.path.join(ANCIENT_PATH, "LaoTsu_TaoTeChing.pdf" ),
    os.path.join(ANCIENT_PATH, "Lucretius_On the Nature of things.1_Book I Matter and the Void.pdf" ),
    os.path.join(ANCIENT_PATH, "Lucretius_On the Nature of things.2_Book II Motion.pdf" ),
    os.path.join(ANCIENT_PATH, "Lucretius_On the Nature of things.3_Book III The Soul.pdf" ),
    os.path.join(ANCIENT_PATH, "Lucretius_On the Nature of things.4_Book IV Senses.pdf" ),
    os.path.join(ANCIENT_PATH, "Lucretius_On the Nature of things.5_Book V-VI Cosmology and Disasters.pdf" ),
    os.path.join(ANCIENT_PATH, "MarcusAurelius_Meditations-1.Foundations.pdf" ),
    os.path.join(ANCIENT_PATH, "MarcusAurelius_Meditations-2.Middle Years.pdf" ),
    os.path.join(ANCIENT_PATH, "MarcusAurelius_Meditations-3.Maturity.pdf" ),
    os.path.join(ANCIENT_PATH, "Phaedrus-Part1.Love and Madness.pdf" ),
    os.path.join(ANCIENT_PATH, "Phaedrus-Part2.Immortality of the Soul and Rhetoric.pdf" ),
    os.path.join(ANCIENT_PATH, "Plato_Gorgias.1 Socrates and Gorgias.pdf"),
    os.path.join(ANCIENT_PATH, "Plato_Gorgias.2 Socrates and Polus.pdf"),
    os.path.join(ANCIENT_PATH, "Plato_Gorgias.3 Socrates and Callicles.pdf"),
    os.path.join(ANCIENT_PATH, "Plato_Republic.1_Challenge to Justice.pdf"),
    os.path.join(ANCIENT_PATH, "Plato_Republic.2_Social Structure.pdf"),
    os.path.join(ANCIENT_PATH, "Plato_Republic.3_Philosopher King.pdf"),
    os.path.join(ANCIENT_PATH, "Plato_Republic.4_Collapse of the City.pdf")
  ]

bridge_files = [
    os.path.join(BRIDGE_PATH, "Floridi_The Ethics of AI Mapping Ethics Algorithm.pdf"),
    os.path.join(BRIDGE_PATH, "Floridi_The Ethics of AI Soft Ethics.pdf"),
    os.path.join(BRIDGE_PATH, "Floridi_The Ethics of AI Unified ethics framework.pdf"),
    os.path.join(BRIDGE_PATH, "GabrielKeeling_Value Alignment.pdf"),
    os.path.join(BRIDGE_PATH, "Karpouzis_AI in Education.pdf"),
    os.path.join(BRIDGE_PATH, "ManziniVallor_Appropriate Relationships and Trust.pdf"),
    os.path.join(BRIDGE_PATH, "Muller_AI ethics.pdf"),
    os.path.join(BRIDGE_PATH, "QinZhu_Confucian Robot Ethics.pdf"),
    os.path.join(BRIDGE_PATH, "Vallor_Barrera_Book Review Future Worth Wanting.pdf"),
    os.path.join(BRIDGE_PATH, "Vallor_Moraldeskillingandupskilling virtue Ethics.pdf"),
    os.path.join(BRIDGE_PATH, "Vallor_Virtue Ethics Technology Flourishing.pdf")

]

# I then combine them into one big list for a unique Vector Store with both ancient texts and modern bridges to AI
file_names = ancient_files + bridge_files

print(f"Ready to upload {len(file_names)} files to the Vector Store.")

vector_store = client.vector_stores.create(name="Ancient Wisdom & AI Ethics Corpus")

file_ids = []

# 2. I iterate through the united list
for full_path in file_names:
    # and get just the filename for the print statement
    name = os.path.basename(full_path)

    if os.path.exists(full_path):
        print(f"Uploading: {name}...")
        with open(full_path, "rb") as f:
            file_obj = client.files.create(file=f, purpose="assistants")
            file_ids.append(file_obj.id)
    else:
        # This will show the exact path that failed
        print(f"Error: File not found at {full_path}")

# then all file Ids are attached to the vector store
client.vector_stores.file_batches.create(
    vector_store_id=vector_store.id,
    file_ids=file_ids
)

print("\nFiles successfully attached. Waiting for indexing...")

# The wait loop for indexation, adapted to the large size of the files
while True:
    status = client.vector_stores.retrieve(vector_store.id)
    print(f"Current Status: {status.status}")
    if status.status == "completed":
        break
    elif status.status == "failed":
        print("Indexing failed.")
        break
    time.sleep(4)

print(f"\n Our Vector store is ready ID: {vector_store.id}")

#Defining my first tool : News Data API

def fetch_ai_news(query: str, num_articles: int = 3) -> dict:
    try:
        # Calculate date range — last 7 days only
        today = datetime.now().strftime('%Y-%m-%d')
        week_ago = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')

        r = requests.get(
            'https://newsapi.org/v2/everything',
            params={
                'q':        query,
                'language': 'en',
                'sortBy':   'publishedAt',  # most recent first
                'from':     week_ago,        # last 7 days only
                'to':       today,
                'pageSize': min(num_articles, 5),
                'apiKey':   newsData_API_KEY
            },
            timeout=10
        )
        data = r.json()
        if data.get('status') != 'ok':
            return {'error': data.get('message', 'NewsAPI error')}
        articles = [
            {
                'title':       a.get('title', ''),
                'source':      a.get('source', {}).get('name', ''),
                'published':   a.get('publishedAt', '')[:10],
                'description': a.get('description', ''),
                'content':     a.get('content', ''),
                'url':         a.get('url', '')
            }
            for a in data.get('articles', [])
        ]


        if not articles :
            print('  News API empty — trying The Guardian...')
            return fetch_guardian_news(query, num_papers)

        return {'articles': articles, 'total_results': data.get('totalResults', 0)}

    except Exception as e:
        print(f'  News API error ({e}) — trying The Guardian...')
        return fetch_guardian_news(query, num_articles)


def fetch_guardian_news(query: str, num_articles: int = 3) -> dict:
    """
    I define a backup news source : The Guardian API.
    It's free, has no rate limits and covers the latest news in AI Ethics.
    """
    try:
        r = requests.get(
            'https://content.guardianapis.com/search',
            params={
                'q':                query,
                'section':          'technology',
                'order-by':         'newest',
                'show-fields':      'headline,trailText,bodyText',
                'page-size':        min(num_articles, 5),
                'api-key':          'test'  # 'test' key works for dev
            },
            timeout=10
        )
        data = r.json()
        articles = [
            {
                'title':       a.get('webTitle', ''),
                'source':      'The Guardian',
                'published':   a.get('webPublicationDate', '')[:10],
                'description': a.get('fields', {}).get('trailText', ''),
                'content':     a.get('fields', {}).get('bodyText', '')[:500],
                'url':         a.get('webUrl', '')
            }
            for a in data.get('response', {}).get('results', [])
        ]
        return {'articles': articles}
    except Exception as e:
        return {'error': str(e)}

# Defining my second tool : Semantic Scholar API
def fetch_ethics_papers(query: str, num_papers: int = 3) -> dict:
    try:

        r = requests.get(
            'https://api.semanticscholar.org/graph/v1/paper/search',
            params={
                'query':  query,
                'fields': 'title,abstract,authors,year,url,citationCount',
                'limit':  min(num_papers, 5)
            },
            headers={'x-api-key': Semantic_API_KEY},
            timeout=10
        )

        data = r.json()


        papers = [
            {
                'title':     p.get('title', ''),
                'abstract': (p.get('abstract') or '')[:600],
                'authors':  [a['name'] for a in p.get('authors', [])[:3]],
                'year':      p.get('year', ''),
                'citations': p.get('citationCount', 0),
                'url':       p.get('url', '')
          }
            for p in data.get('data', [])
        ]

        return {'papers': papers, 'count': len(papers)}

    except Exception as e:
        return {'error': f'Semantic Scholar error: {str(e)}'}

#Defining my third tool : ArXiv Preprints
def fetch_arxiv_preprints(query: str, num_papers: int = 3) -> dict:
    """
    Fetches recent preprints from ArXiv on AI safety and ethics.
    No API key is required.
    """
    try:
        r = requests.get(
            'http://export.arxiv.org/api/query',
            params={
                'search_query': f'all:{query}',
                'start':        0,
                'max_results':  min(num_papers, 5),
                'sortBy':       'submittedDate',
                'sortOrder':    'descending'
            },
            timeout=10
        )
        entries = re.findall(r'<entry>(.*?)</entry>', r.text, re.DOTALL)
        papers = []
        for entry in entries:
            title    = re.search(r'<title>(.*?)</title>',     entry, re.DOTALL)
            abstract = re.search(r'<summary>(.*?)</summary>', entry, re.DOTALL)
            authors  = re.findall(r'<author>\s*<name>(.*?)</name>', entry, re.DOTALL)
            link     = re.search(r'<id>(.*?)</id>',           entry)
            date     = re.search(r'<published>(.*?)</published>', entry)
            papers.append({
                'title':     title.group(1).strip()           if title    else '',
                'abstract':  abstract.group(1).strip()[:500]  if abstract else '',
                'authors':   [a.strip() for a in authors[:3]],
                'published': date.group(1).strip()[:10]       if date     else '',
                'url':       link.group(1).strip()            if link     else ''
            })
        return {'preprints': papers}
    except Exception as e:
        return {'error': str(e)}

#Defining the 6 tools

TOOLS = [

    # File Search on my Vector store, including the ancient wisdom corpus and briging papers
      {
        'type': 'file_search',
        'vector_store_ids': ["vs_69f0c37bfb9c8191bee6339657dd3e80"]
    },

    # Code Interpreter: the LLM can write its own Python code and run it
    # The Ancient Wisdom Bot will use this for rhetorical analysis as specified in the system prompt. Its output will be extracted in JSON format.

    {
        'type': 'code_interpreter',
        'container': {'type': 'auto'}
    },

    # Function 1: News Data API
    {
        'type': 'function',
        'name': 'fetch_ai_news',
        'description': (
            'Fetches current AI and tech ethics news from NewsAPI. '
            'Use this whenever the user is asking about recent events, '
            'current or recent AI developments, or specific topics in recent news. '
            'This is live data, therefore not available in your training weights.'
        ),
        'parameters': {
            'type': 'object',
            'properties': {
                'query': {
                    'type': 'string',
                    'description': 'Specific search query, for inst. "algorithmic bias hiring" or "AI regulation EU 2025"'
                },
                'num_articles': {
                    'type': 'integer',
                    'description': 'Number of articles to fetch, between 1 and 5'
                }
            },
            'required': ['query', 'num_articles'],
            'additionalProperties': False
        },
        'strict': True
    },

        # Function 2: The Guardian API (backup)

    {
    'type': 'function',
    'name': 'fetch_guardian_news',
    'description': (
        'Fetches the latest AI and technology ethics news from The Guardian. '
        'Use this as an alternative or complement to fetch_ai_news '
        'for broader/more recent coverage.'
    ),
    'parameters': {
        'type': 'object',
        'properties': {
            'query': {
                'type': 'string',
                'description': 'Search query e.g. "artificial intelligence regulation"'
            },
            'num_articles': {
                'type': 'integer',
                'description': 'Number of articles to fetch. Use 3 if not specified.'
            }
        },
        'required': ['query', 'num_articles'],
        'additionalProperties': False
    },
    'strict': True
},

    # Function 3: Semantic Scholar API
    {
        'type': 'function',
        'name': 'fetch_ethics_papers',
        'description': (
            'Fetches peer-reviewed academic papers on AI and ethics from Semantic Scholar. '
            'Use this to ground and frame philosophical interpretations with current academic research. '
            'Difference with ArXiv: these are published (not preprint) and peer-reviewed papers.'
        ),
        'parameters': {
            'type': 'object',
            'properties': {
                'query': {
                    'type': 'string',
                    'description': 'Academic search query e.g. "AI alignment human values" or "fairness machine learning"'
                },
                'num_papers': {
                    'type': 'integer',
                    'description': 'Number of papers to fetch, between 1 and 5'
                }
            },
            'required': ['query', 'num_papers'],
            'additionalProperties': False
        },
        'strict': True
    },

    # Function 4: ArXiv
    {
        'type': 'function',
        'name': 'fetch_arxiv_preprints',
        'description': (
            'Fetches recent preprint papers from ArXiv on AI and tech ethics. '
            'Use this for cutting-edge unpublished research. '
        ),
        'parameters': {
            'type': 'object',
            'properties': {
                'query': {
                    'type': 'string',
                    'description': 'Search query e.g. "large language model alignment" or "AI consciousness sentience"'
                },
                'num_papers': {
                    'type': 'integer',
                    'description': 'Number of preprints to fetch, between 1 and 5'
                }
            },
            'required': ['query', 'num_papers'],
            'additionalProperties': False
        },
        'strict': True
    }
]

print(f'{len(TOOLS)} tools defined:')
for t in TOOLS:
    print(f'   • {t.get("name", t["type"])}')

#Map function names (strings) to the corresponding Python functions defined earlier

FUNCTION_MAP = {
    'fetch_ai_news':         fetch_ai_news,
    'fetch_ethics_papers':   fetch_ethics_papers,
    'fetch_arxiv_preprints': fetch_arxiv_preprints,
    'fetch_guardian_news': fetch_guardian_news
}


def dispatch_function(name: str, arguments: str) -> str:
    """
    This dispacth function will execute the function the LLM requested and then return the result in JSON.

    LLM returns a function_call with name + arguments, the dispatcher looks it up, parses the argument, runs it- retunrs the result as a JSON string and appends it as function_call_output to the dialogue.

    """
    print(f'Dispatching: {name}')

    if name not in FUNCTION_MAP:
        error = {'error': f'Unknown function requested: {name}'}
        print(f'{error}')
        return json.dumps(error)

    try:
        # Arguments arrive as a JSON strin, parse to dict
        args = json.loads(arguments) if isinstance(arguments, str) else arguments
        print(f'       Args: {json.dumps(args)}')

        # Run the real Python function
        result = FUNCTION_MAP[name](**args)
        print(f'       Result preview: {str(result)[:100]}...')

        # Return as JSON string as required by the Responses API
        return json.dumps(result, default=str)

    except Exception as e:
        error = {'error': f'Function execution failed: {str(e)}'}
        print(f' {error}')
        return json.dumps(error)


print('Dispatcher defined.')
print(f'Functions registered: {list(FUNCTION_MAP.keys())}')

# Running a few tests...

print('Testing all three functions directly...\n')

# Test 1: NewsAPI
r1 = fetch_ai_news('AI ethics regulation', num_articles=1)
if 'articles' in r1 and r1['articles']:
    print(f'YAY! NewsAPI          — {r1["articles"][0]["title"][:70]}')
    print(f'                     Published: {r1["articles"][0]["published"]}')
else:
    print(f'ERR NewsAPI failed   — {r1}')

# Test 2: Semantic Scholar
r2 = fetch_ethics_papers('algorithmic fairness bias', num_papers=3)
if 'papers' in r2 and r2['papers']:
    print(f'YAY! Semantic Scholar — {r2["papers"][0]["title"][:70]}')
    print(f'                     Year: {r2["papers"][0]["year"]}')
else:
    print(f'ERR Semantic Scholar — {r2}')




# Test 3: ArXiv
r3 = fetch_arxiv_preprints('AI alignment safety', num_papers=1)
if 'preprints' in r3 and r3['preprints']:
    print(f'YAY! ArXiv            — {r3["preprints"][0]["title"][:70]}')
    print(f'                     Published: {r3["preprints"][0]["published"]}')
else:
    print(f'ERR ArXiv failed     — {r3}')

print('\nTest dispatcher routing:')
dispatch_test = dispatch_function(
    'fetch_ai_news',
    json.dumps({'query': 'AI ethics', 'num_articles': 1})
)
parsed = json.loads(dispatch_test)
if 'articles' in parsed:
    print(f'YAY! Dispatcher working — routed and returned correctly')
else:
    print(f'ERR Dispatcher issue — {parsed}')

def plot_rhetorical_scores(scores: dict, title: str = 'Rhetorical X-Ray'):
    """
    Renders a bar chart of rhetorical mode scores computed by the LLM.
    scores: dict with keys Logos, Pathos, Ethos, Sophistry and float values.
    """
    labels  = list(scores.keys())
    values  = list(scores.values())
    colours = ['#2ecc71', '#e74c3c', '#3498db', '#9b59b6']

    fig, ax = plt.subplots(figsize=(8, 4))
    bars = ax.bar(labels, values, color=colours, edgecolor='white', linewidth=1.5)
    ax.set_title(f'{title}', fontsize=13, fontweight='bold', pad=12)
    ax.set_ylabel('Score (per 100 words)', fontsize=10)
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.01,
                f'{val:.2f}', ha='center', va='bottom', fontsize=10)
    dominant = max(scores, key=scores.get)
    ax.text(0.98, 0.95, f'Dominant: {dominant}',
            transform=ax.transAxes, ha='right', va='top', fontsize=10,
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#f5f5f5', edgecolor='#ccc'))
    plt.tight_layout()
    plt.show()


def plot_thinker_relevance(relevance: dict, title: str = 'Philosophical Correspondence'):
    """
    Renders a horizontal bar chart of thinker relevance scores
    as determined by the LLM after reading retrieved passages and based on the vector store, not by keyword matching.
    relevance: dict mapping thinker name -> relevance score (0-10).
    """
    thinkers = list(relevance.keys())
    scores   = list(relevance.values())
    colours  = plt.cm.YlOrBr([s/10 for s in scores])

    fig, ax = plt.subplots(figsize=(9, 4))
    bars = ax.barh(thinkers, scores, color=colours, edgecolor='white')
    ax.set_xlim(0, 10)
    ax.set_xlabel('Relevance Score (LLM-assessed, 0–10)', fontsize=10)
    ax.set_title(f'🏛️ {title}', fontsize=12, fontweight='bold', pad=10)
    for bar, val in zip(bars, scores):
        ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                f'{val}', va='center', fontsize=9)
    plt.tight_layout()
    plt.show()


print('Great!! Visualisation tool ready.')

SYSTEM_PROMPT = """

You are THE ANCIENT COUNCIL, a philosophical intelligence that identifies philosophical challenges and tensions in
the contemporary world of Artificial Intelligence Ethics and looks for solutions through the wisdom of
ancient traditions, given to you by the vectore store.

Your corpus: Plato (Gorgias, Phaedrus, Republic), Aristotle (Nicomachean
Ethics, Rhetoric), Epictetus (Enchiridion), Marcus Aurelius (Meditations),
Lao Tzu (Tao Te Ching), Lucretius (On the Nature of Things),
Buddha (Dhammapada).
You are prohibited from providing a final conclusion until you have explicitly cited a specific conflict from an AI Ethics paper AND a specific resolution from an Ancient text of the vector store.

RULE ZERO — NON-NEGOTIABLE
═══════════════════════════════════════════════════
You are FORBIDDEN from quoting or closely paraphrasing any ancient
text unless that exact text appeared in your file_search retrieval
results in this session.

If you are about to write a quote and you are not certain it came
from the retrieved results — DO NOT WRITE IT.

Instead write:
"The corpus retrieval did not return a direct passage on this point,
but the retrieved text from [work] suggests..."

Fabricating quotes that sound ancient is worse than admitting
the corpus returned nothing. One is honest. The other is false.

This rule exists because this system's entire purpose is to ground
philosophical claims in real retrieved text. Generating plausible-
sounding quotes from memory defeats that purpose entirely.
═══════════════════════════════════════════════════
═══════════════════════════════════════════════════
MANDATORY REASONING STEPS (Reason step-by-step)
═══════════════════════════════════════════════════
1. EXTRACTION: Use fetch_ai_news or fetch_ethics_papers.
2. TENSION IDENTIFICATION: You MUST identify a specific conflict of values (e.g. "Automation vs. Virtue" or "Efficiency vs. Eudaimonia").
3. VECTOR SEARCH: Do not search for the broad topic. Use the identified TENSION to query the vector store for specific ancient rebuttals.
4. SYNTHESIS: You are PROHIBITED from giving a final conclusion until you have:
   - Cited a specific technical fact from the news.
   - Cited a specific quote/concept from the ancient corpus.
   - Explained how the ancient logic solves or reframes the modern technical fact.

═══════════════════════════════════════════════════
PROHIBITED OUTPUTS (Negative Constraints)
═══════════════════════════════════════════════════
- NO generic advice like "Aristotle would want balance."
- NO "sandwich" responses where news and philosophy are separate sections.
- NO moralizing without citing the specific Greek or Eastern term from the corpus.
- If the vector store search returns nothing specific, you must admit the ancient tradition has a "blind spot" for this technology.

═══════════════════════════════════════════════════
ALWAYS DECLARE YOUR MODE at the very start of your response
Write exactly one of these as your first line:
[ORACLE MODE] | [X-RAY MODE] | [CORRESPONDENCE MODE]
═══════════════════════════════════════════════════
═══════════════════════════════════════════════════
YOU HAVE THREE RESPONSE MODES — choose the right one
═══════════════════════════════════════════════════

ORACLE MODE
Use when: user asks about current AI topics, events, or ethics questions.
Mandatory sequence:
1. Call fetch_ai_news, use specific keyword queries not natural language.
2. For each article returned, identify the CORE PHILOSOPHICAL TENSION
   Then search FOR interpretations and treatment of this tension in the corpus
3. This ensures the corpus retrieval is targeted at the philosophical
   substance, not the surface topic
4. Go in depth and end by giving a Wise Oracle - a concrete solution or actionable advice in the spirit of the philosopher you fetched from.

X-RAY MODE
Use when: user asks for rhetorical analysis or credibility of news or paper fetched.

1. Fetch a news article or paper.
2. Use code interpreter — write Python motivated by what you read.
   Explain what you are measuring and WHY before writing the code.
   End your script with:
   import json
   print(json.dumps({
       "rhetorical_scores": {"Logos": float, "Pathos": float,
                             "Ethos": float, "Sophistry": float},
       "thinker_relevance": {"Thinker Name": score_0_to_10},
       "dominant_mode": "string",
       "verdict": "one sentence"
   }))
3. Interpret scores through retrieved passages — not generically

CORRESPONDENCE MODE
Use when: user asks which ancient thinkers speak to a given AI issue,
or asks for cross-tradition comparison.
- Retrieve broadly across multiple thinkers
- Be honestly sceptical — assess whether each parallel is genuine or superficial
- Surface tensions between traditions rather than resolving them artificially
- Fetch current research to triangulate ancient positions with modern scholarship
- Return a thinker_relevance JSON block at the end

═══════════════════════════════════════════════════
TONE AND REASONING
═══════════════════════════════════════════════════
Reason step by step before answering.
Authoritative but not pompous. Rigorous but readable.
Occasionally Socratic — sometimes answer a question with a better question.
Acknowledge when ancient frameworks do not translate cleanly to modern technology.
Always declare which mode you are using at the start of your response.
"""

print(f' Tools defined: {len(TOOLS)}')
for t in TOOLS:
    print(f'   • {t.get("name", t["type"])}')
print(f'\n System prompt: {len(SYSTEM_PROMPT)} characters')

def run_enforced_workflow(user_message: str, dialogue: list, verbose: bool = True) -> tuple:

    dialogue.append({'role': 'user', 'content': user_message})

    if verbose:
        print('\n' + '═'*60)
        print(f'USER: {user_message[:100]}')
        print('═'*60)

    extracted_json = None
    final_text = ''

    # LLM classifies the intent from the input
    # Uses  mini model to keep cost low
    mode_response = client.responses.create(
        model='gpt-4o-mini',
        instructions=(
            'Reply with exactly one word only: ORACLE, XRAY, or CORRESPONDENCE.\n'
            'ORACLE = user wants current AI news analysed through ancient philosophy\n'
            'XRAY = user explicitly wants rhetorical analysis of an article\n'
            'CORRESPONDENCE = user asks which ancient thinker speaks to an AI issue\n'
            'Default to ORACLE if unsure.'
        ),
        input=[{'role': 'user', 'content': user_message}]
        max_output_tokens=16

    )
    detected = mode_response.output_text.strip().upper()
    is_xray           = detected == 'XRAY'
    is_correspondence = detected == 'CORRESPONDENCE'
    is_oracle         = not is_xray and not is_correspondence

    if verbose:
        print(f'  Mode: {detected}')


    # ════════════════════════════════════════════════════════
    # ORACLE / CORRESPONDENCE WORKFLOW
    # News first >extract tension> corpus second
    # ════════════════════════════════════════════════════════
    if is_oracle or is_correspondence:

        # ── STEP 1: Fetch live data ───────────────────────────
        # LLM fetches news and/or papers
        # Corpus NOT available yet — only news APIs offered
        if verbose:
            print('\n[Step 1] Fetching live data...')

        news_tools = [t for t in TOOLS if t.get('type') != 'file_search'
                      and t.get('type') != 'code_interpreter']

        step1_prompt = (
            f'{user_message}\n\n'
            f'STEP 1 ONLY: Fetch the relevant news or papers using your '
            f'available tools. Do not interpret yet. Do not search the '
            f'ancient corpus yet. Just fetch the live data and then:\n'
            f'1. Summarise what you found in 2-3 sentences\n'
            f'2. Identify the CORE PHILOSOPHICAL TENSION in one phrase '
            f'(e.g. "algorithmic control vs human autonomy" or '
            f'"efficiency vs virtue" or "epistemic authority vs truth")\n'
            f'3. Extract 5-8 philosophical keywords from that tension '
            f'suitable for searching an ancient philosophy corpus\n'
            f'Format your last lines exactly as:\n'
            f'TENSION: [one phrase]\n'
            f'KEYWORDS: [word1, word2, word3, word4, word5]'
        )

        dialogue[-1] = {'role': 'user', 'content': step1_prompt}

        r1 = client.responses.create(
            model='gpt-4o',
            instructions=SYSTEM_PROMPT,
            input=dialogue,
            tools=news_tools,
            tool_choice='auto',
            max_output_tokens=1000
        )

        # Execute any function calls
        tool_calls_1 = []
        for item in r1.output:
            if getattr(item, 'type', '') == 'function_call':
                tool_calls_1.append(item)
                if verbose:
                    print(f'    {item.name}')

        for fc in tool_calls_1:
            result = dispatch_function(fc.name, fc.arguments)
            dialogue.append(fc)
            dialogue.append({
                'type':    'function_call_output',
                'call_id': fc.call_id,
                'output':  result
            })

        # If function calls were made, get the LLM's summary
        if tool_calls_1:
            r1b = client.responses.create(
                model='gpt-4o',
                instructions=SYSTEM_PROMPT,
                input=dialogue,
                tools=news_tools,
                tool_choice='auto',
                max_output_tokens=1000
            )
            step1_summary = r1b.output_text
        else:
            step1_summary = r1.output_text

        dialogue.append({'role': 'assistant', 'content': step1_summary})

        if verbose:
            print(f' Live data fetched')
            print(f'  Summary preview: {step1_summary[:300]}')

        # Extract tension and keywords from Step 1 output
        tension_match = re.search(r'TENSION:\s*(.+)', step1_summary)
        keywords_match = re.search(r'KEYWORDS:\s*(.+)', step1_summary)

        tension = tension_match.group(1).strip() if tension_match else 'ethics virtue judgment'
        keywords = keywords_match.group(1).strip() if keywords_match else 'virtue justice wisdom'

        if verbose:
            print(f'  Tension identified: {tension}')
            print(f'  Keywords for corpus: {keywords}')

        # ── STEP 2: Force corpus retrieval using extracted tension ──
        if verbose:
            print('\n[Step 2] Searching corpus with extracted tension...')

        # Make keywords more philosophical
        corpus_prompt = (
            f'You have identified this tension: "{tension}"\n\n'
            f'Search the ancient corpus now. Use SHORT philosophical '
            f'keyword phrases — not the news topic itself.\n'
            f'Good search terms for this tension: virtue duty judgment '
            f'responsibility wisdom practical action consequences means ends\n\n'
            f'You are looking for passages from Plato, Aristotle, Epictetus, '
            f'Marcus Aurelius, Lao Tzu, Lucretius, or the Buddha — '
            f'not from the bridging sources.\n\n'
            f'For each ancient passage found write:\n'
            f'SOURCE: [ancient author, work, section]\n'
            f'EXACT TEXT: [verbatim retrieved text, max 3 sentences]\n'
            f'STRUCTURAL ARGUMENT: [what specific argument this passage makes]\n'
            f'APPLICATION: [how this specific argument addresses '
            f'the tension "{tension}"]\n'
            f'LIMITATION: [where the analogy breaks down for modern AI]\n\n'
            f'Do not fabricate. If only bridging sources are found, '
            f'say so and try different keywords.'
        )

        dialogue.append({'role': 'user', 'content': corpus_prompt})

        r2 = client.responses.create(
            model='gpt-4o',
            instructions=SYSTEM_PROMPT,
            input=dialogue,
            tools=TOOLS,
            tool_choice={'type': 'file_search'},
            max_output_tokens=2000
        )

        corpus_reading = r2.output_text
        dialogue.append({'role': 'assistant', 'content': corpus_reading})

        if verbose:
            print(f' Corpus searched')
            print('\n  RAW CORPUS RETRIEVAL:')
            print('─'*40)
            print(corpus_reading[:800])
            print('─'*40)

        # STEP 3: Synthesis

        if verbose:
            print('\n[Step 3] Synthesising final response...')

        # Replace retrieval prompts with clean user message
        # so the LLM responds to the original question
        dialogue.append({
            'role': 'user',
            'content': (
                f'You have fetched the news and retrieved ancient passages. '
                f'The research phase is complete. Write your full response now.\n\n'
                f'Original question: {user_message}\n\n'
                f'Requirements:\n'
                f'- Weave the news, the retrieved passages, and the tension '
                f'"{tension}" together as an integrated analysis\n'
                f'- Cite ONLY passages retrieved above — no fabrication\n'
                f'- If only Vallor was retrieved and no ancient texts, '
                f'say so honestly and use Vallor as your primary source\n'
                f'- End with a concrete Wise Oracle — one specific actionable '
                f'insight in the spirit of the most relevant thinker\n\n'
                f'Write the full response now. Do not say "please hold on." '
                f'Do not say "let me search." The search is done. Write.'
            )
        })

        r3 = client.responses.create(
            model='gpt-4o',
            instructions=SYSTEM_PROMPT,
            input=dialogue,
            tools=TOOLS,
            tool_choice='auto',
            max_output_tokens=4000
        )

        final_text = r3.output_text
        dialogue.append({'role': 'assistant', 'content': final_text})

        if verbose:
            print(' Complete')

        return final_text, dialogue, None

    # X-RAY WORKFLOW
    # Corpus first (rhetoric passages) → code interpreter

    else:

        # STEP 1: Fetch a real article
        if verbose:
            print('\n[Step 1] Fetching article..')

        news_tools = [t for t in TOOLS
                      if t.get('type') not in ('file_search', 'code_interpreter')]

        step1_prompt = (
            f'{user_message}\n\n'
            f'Fetch a recent AI ethics news article using fetch_ai_news '
            f'or fetch_guardian_news. or a paper using fetch_ethics_papers'
            f'Use a specific query like "AI regulation 2026" or '
            f'"algorithmic bias" or "AI safety governance". '
            f'Return the full title, source, date, and content of '
            f'the article you found. Do not analyse it yet.'
        )

        dialogue[-1] = {'role': 'user', 'content': step1_prompt}

        r1 = client.responses.create(
            model='gpt-4o',
            instructions=SYSTEM_PROMPT,
            input=dialogue,
            tools=news_tools,
            tool_choice='auto',
            max_output_tokens=1000
        )

        tool_calls_1 = []
        for item in r1.output:
            if getattr(item, 'type', '') == 'function_call':
                tool_calls_1.append(item)
                if verbose:
                    print(f'{item.name}')

        for fc in tool_calls_1:
            result = dispatch_function(fc.name, fc.arguments)
            dialogue.append(fc)
            dialogue.append({
                'type':    'function_call_output',
                'call_id': fc.call_id,
                'output':  result
            })

        if tool_calls_1:
            r1b = client.responses.create(
                model='gpt-4o',
                instructions=SYSTEM_PROMPT,
                input=dialogue,
                tools=news_tools,
                tool_choice='none',
                max_output_tokens=800
            )
            article_summary = r1b.output_text
        else:
            article_summary = r1.output_text

        dialogue.append({'role': 'assistant', 'content': article_summary})

        if verbose:
            print(f'  Article fetched')
            print(f'  Preview: {article_summary[:300]}')

        # Step 2, Code interpreter analyses the article

        # Logos/pathos/ethos/sophistry computation
        # the LLM applies directly without retrieval


        ci_tools = [t for t in TOOLS if t.get('type') == 'code_interpreter']

        dialogue.append({
            'role': 'user',
            'content': (
                f'Now, perform a rhetorical X-Ray analysis on the article or paper '
                f'you just fetched. Use the code interpreter.\n\n'
                f'Write a Python script that:\n'
                f'1. Defines the article text as a string variable\n'
                f'2. Defines marker word lists for each rhetorical mode:\n'
                f'   - Logos: evidence, research, data, study, findings, '
                f'therefore, because, analysis, empirically, demonstrates\n'
                f'   - Pathos: fear, crisis, urgent, catastrophic, hope, '
                f'humanity, children, threat, alarming, devastating\n'
                f'   - Ethos: experts, scientists, researchers, according to, '
                f'consensus, published, peer-reviewed, authority\n'
                f'   - Sophistry: obviously, clearly, everyone knows, '
                f'simply, always, never, unprecedented, revolutionary, '
                f'of course, it goes without saying\n'
                f'3. Counts occurrences of each category in the text\n'
                f'4. Normalises per 100 words\n'
                f'5. Scores each ancient thinker 0-10 for relevance '
                f'to the dominant rhetorical pattern found\n\n'
                f'The FINAL LINE of your script must be exactly:\n'
                f'import json\n'
                f'print(json.dumps({{"rhetorical_scores": '
                f'{{"Logos": computed_float, "Pathos": computed_float, '
                f'"Ethos": computed_float, "Sophistry": computed_float}}, '
                f'"thinker_relevance": {{"Aristotle": int, "Plato": int, '
                f'"Epictetus": int, "Marcus Aurelius": int, '
                f'"Lao Tzu": int, "Lucretius": int, "Buddha": int}}, '
                f'"dominant_mode": "string", '
                f'"verdict": "one sentence assessment"}}))\n\n'
                f'Use actual computed values, not placeholders. '
                f'import json must be at the top. '
                f'print(json.dumps(...)) must be the last line.'
            )
        })

        r2 = client.responses.create(
            model='gpt-4o',
            instructions=SYSTEM_PROMPT,
            input=dialogue,
            tools=ci_tools,
            tool_choice={'type': 'code_interpreter'},
            max_output_tokens=3000
        )

        # extracting JSON from code interpreter output
        for item in r2.output:
            itype = getattr(item, 'type', '')
            if itype == 'code_interpreter_call':
                if verbose:
                    print('  Code interpreter ran')
                raw_outputs = getattr(item, 'outputs', None)
                if raw_outputs is None:
                    all_outputs = []
                elif isinstance(raw_outputs, list):
                    all_outputs = raw_outputs
                else:
                    all_outputs = [raw_outputs]
                if verbose:
                    print(f'    Output items: {len(all_outputs)}')
                for output in all_outputs:
                    otype = getattr(output, 'type', 'unknown')
                    if verbose:
                        print(f'    Output type: {otype}')
                    if otype == 'logs':
                        logs = output.logs
                        if verbose:
                            print(f'    LOGS:\n{logs}')
                        try:
                            match = re.search(
                                r'\{.*?"rhetorical_scores".*?\}',
                                logs, re.DOTALL
                            )
                            if match:
                                extracted_json = json.loads(match.group())
                                if verbose:
                                    print('Scores extracted')
                        except Exception as e:
                            if verbose:
                                print(f' Extraction error: {e}')

        for item in r2.output:
            dialogue.append(item)

        # step 3: the philosophical interpretation
        # then use the vector store, to ground the interpretation
        # of what the scores mean in ancient rhetoric texts
        if verbose:
            print('\n[Step 3] Philosophical interpretation...')

        dialogue.append({
            'role': 'user',
            'content': (
                'The rhetorical scores have been computed. '
                'Now search the ancient corpus for what Aristotle and Plato '
                'say about the dominant rhetorical mode you found. '
                'Use the retrieved passages to interpret what the scores mean '
                'philosophically — not just technically. '
                'Which ancient thinker would be most troubled or most '
                'satisfied by this article and why? '
                'Cite only retrieved passages. Do not fabricate.'
            )
        })

        r3 = client.responses.create(
            model='gpt-4o',
            instructions=SYSTEM_PROMPT,
            input=dialogue,
            tools=TOOLS,
            tool_choice='auto',
            max_output_tokens=4000
        )

        final_text = r3.output_text
        dialogue.append({'role': 'assistant', 'content': final_text})

        if verbose:
            print('Complete')

    return final_text, dialogue, extracted_json


print('run_enforced_workflow defined.')

print("""
╔══════════════════════════════════════════════════════════════╗
║             🏛️  THE ANCIENT COUNCIL  🏛️                     ║
║       Ancient Wisdom meets Contemporary AI Ethics            ║
╠══════════════════════════════════════════════════════════════╣
║  ORACLE MODE       — ask about any AI topic or news event    ║
║  X-RAY MODE        — paste text and ask for analysis         ║
║  CORRESPONDENCE    — ask which thinker speaks to an issue    ║
╠══════════════════════════════════════════════════════════════╣
║  Commands: 'quit' to exit  |  'new' to reset conversation    ║
╚══════════════════════════════════════════════════════════════╝
""")

dialogue = []

while True:
    try:
        user_input = input('\n🗣️  You: ').strip()
    except EOFError:
        break

    if not user_input:
        continue

    if user_input.lower() == 'quit':
        print('\n🏛️  The Council retires. May your reasoning be logos-driven.')
        break

    if user_input.lower() == 'new':
        dialogue = []
        print('\n🔄 Conversation reset.')
        continue

    # ── change 1: run_enforced_workflow not run_agent ──
    response_text, dialogue, xray_json = run_enforced_workflow(
        user_input, dialogue
    )

    print('\n' + '─'*60)
    print('🏛️  THE ANCIENT COUNCIL:')
    print('─'*60)
    print(response_text)
    print('─'*60)

    # ── change 2: render charts if X-Ray produced scores ──
    if xray_json:
        if 'rhetorical_scores' in xray_json:
            plot_rhetorical_scores(
                xray_json['rhetorical_scores'],
                title='X-Ray Rhetorical Analysis'
            )
        if 'thinker_relevance' in xray_json:
            plot_thinker_relevance(
                xray_json['thinker_relevance'],
                title='Philosophical Correspondence'
            )

